# Generated by Django 4.2.13 on 2024-06-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hidrometricos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidrometrico',
            name='consumo',
        ),
    ]
