# Generated by Django 4.2.11 on 2024-06-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
