# Generated by Django 4.2.11 on 2024-06-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
            ],
        ),
    ]
