# Generated by Django 4.2.11 on 2024-06-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microbiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coliformes_totais', models.FloatField()),
                ('coliformes_fecais', models.FloatField()),
                ('e_coli', models.FloatField()),
            ],
        ),
    ]
