# Generated by Django 4.2.13 on 2024-06-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_hidricos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microbiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coliformes_totais', models.FloatField()),
                ('coliformes_fecais', models.FloatField()),
                ('e_coli', models.FloatField()),
                ('bacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_hidricos.hidricos')),
            ],
        ),
    ]
