# Generated by Django 4.2.11 on 2024-06-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FisicoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcalinidade_hidroxidos', models.FloatField()),
                ('alcalinidade_bicarbonato', models.FloatField()),
                ('alcalinidade_carbonato', models.FloatField()),
                ('alcalinidade_total', models.FloatField()),
                ('aluminio', models.FloatField()),
                ('cloreto', models.FloatField()),
                ('condutividade_eletrica_25', models.FloatField()),
                ('cor_verdadeira', models.FloatField()),
                ('cor_aparente', models.FloatField()),
                ('dureza_calcio', models.FloatField()),
                ('dureza_magnesio', models.FloatField()),
                ('dureza_total', models.FloatField()),
                ('estimativa_tds', models.FloatField()),
                ('ferro_total', models.FloatField()),
                ('fluoreto', models.FloatField()),
                ('manganes', models.FloatField()),
                ('nitrato', models.FloatField()),
                ('nitrito', models.FloatField()),
                ('ph', models.FloatField()),
                ('potassio', models.FloatField()),
                ('silica', models.FloatField()),
                ('sodio', models.FloatField()),
                ('solidos_totais', models.FloatField()),
                ('sulfatos', models.FloatField()),
                ('turbidez', models.FloatField()),
                ('oxigenio_dissolvido', models.FloatField()),
                ('cloro_residual_livre', models.FloatField()),
            ],
        ),
    ]
