# Generated by Django 4.2.13 on 2024-08-04 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_fisico_quimicos', '0002_remove_fisicoquimico_alcalinidade_bicarbonato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisicoquimico',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
