# Generated by Django 4.2.13 on 2024-08-05 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_fisico_quimicos', '0003_fisicoquimico_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisicoquimico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
