# Generated by Django 4.2.11 on 2024-06-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_hidricos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(max_length=300)),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('hidricos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps_hidricos.hidricos')),
            ],
        ),
    ]
